<script nonce="_pGIAB025CjQ0qsKYlGdWw">(function(){try{
var _F_toggles_initialize=function(a){(typeof globalThis!=="undefined"?globalThis:typeof self!=="undefined"?self:this)._F_toggles=a||[]};_F_toggles_initialize([0x4000, ]);
/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
/*

 Copyright Google LLC
 SPDX-License-Identifier: Apache-2.0
*/
var l="Edge",aa="client_error_page",q="error",u="function",v="load",w="object",ba="severe",x="string",ca="unhandledrejection",da="unknown",ea="unsupported_browser";function fa(){return function(a){return a}}function y(){return function(){}}function ha(a){return function(b){this[a]=b}}
var ja=function(){var a=null;if(!ia)return a;try{var b=fa();a=ia.createPolicy("goog#html",{createHTML:b,createScript:b,createScriptURL:b})}catch(c){}return a},la=function(){ka===void 0&&(ka=ja());return ka},na=function(a){var b=la();return new ma(b?b.createScriptURL(a):a)},oa=function(a){if(a instanceof ma)return a.g;throw Error("o");},pa=function(){var a=A.navigator;return a&&(a=a.userAgent)?a:""},ra=function(a){return qa?B?B.brands.some(function(b){return(b=b.brand)&&b.indexOf(a)!=-1}):!1:!1},C=
function(a){return pa().indexOf(a)!=-1},D=function(){return qa?!!B&&B.brands.length>0:!1},sa=function(){return D()?!1:C("Opera")},ta=function(){return C("Firefox")||C("FxiOS")},ua=function(){return D()?ra("Chromium"):(C("Chrome")||C("CriOS"))&&!(D()?0:C(l))||C("Silk")},va=function(){return C("iPhone")&&!C("iPod")&&!C("iPad")},Fa=function(){return wa?xa(ya,G[2])>=0:za?xa(ya,G[3])>=0:Aa?!1:Ba?Ca(G[0]):Da||Ea&&Ca("9.5")},Ja=function(a){a=a.j;return Ga.test(a)||Ha.test(a)||Ia.test(a)},Sa=function(a,b){var c=
new H(A.location.href),d=Ja(c),e=b.gapi_version===null?null:Ka();Ma(c,A.GM_SESSION_PATH+"logstreamz");Na(c,"");b={impressionId:a,customData:JSON.stringify(b),defaultData:JSON.stringify({inbox_type:A.GM_INBOX_TYPE,hub_configuration:A.GM_HUB_CONFIGURATION,delegation_request:d,customer_type:A.GM_CUSTOMER_TYPE,browser:A.GM_USER_BROWSER,gapi_version:e,compile_mode:A.GM_COMPILE_MODE,is_cached_html:!!A.GM_IS_CACHED_HTML,build_label:A.GM_BUILD_LABEL,from_moose:!!G[27]})};var h=c.toString();c=new Request(h,
{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:Oa(b)});return fetch(c).then(function(f){f.ok||Pa&&Qa(Pa,Ra,"s`"+a+"`"+f.status);return f.status}).catch(function(f){throw Error("t`"+h,{cause:f});})},Va=function(){switch((new H(A.location.href)).g.get("tf")){case "cm":return 1;case "cv":return 2;case "mip":return 3;case "am":return 4;default:return Ta===void 0&&(Ta=Ua(window.location.href,"usp")),Ta=="dot_new"?5:0}},eb=function(a,b,c){c=c===void 0?da:c;if(b instanceof
Object&&!Object.isFrozen(b)){var d=(d=b.fileName||b.filename||b.sourceURL||A.$googDebugFname||location.href)&&(typeof d===w?d.href:d);try{b.fileName=d}catch(m){}}if(I.o>=3)throw Error("x`"+a);I.o++;try{if(I.i)J(I.j,"y`"+a);else{if(I.j){d=a||"Exception";var e=I.j;Wa||(Wa=new Xa);var h=new Ya(Ra||Za,d,e.g());h.i=!0;var f=I.j,g;if(g=f){var k=h.g;g=f&&k?k.value>=$a(f).value:!1}g&&ab(bb(cb(),f.g()),h)}I.l?I.l.g(b,a,c):I.g&&I.g.length<10&&I.g.push(new db(a,b,c))}}finally{I.o--}},kb=function(a,b,c){b=b===
void 0?"":b;A.GM_showErrorPageCalled=!0;fb.add(a);c||(c=Error(b));var d="Error page requested. errorPageCause="+a+", errorMessage="+b;gb&&Qa(gb,Ra,d);eb(d,c||null,ba);A.GM_DEP===null&&(A.GM_DEP=a,d=0,a===5?d=1:a===13&&(d=2),A.GM_writeErrorPage(d,function(){hb(new ib,a.toString());(A.GM_SLF||y())();jb(a,b,c);A.document.getElementById("detailed_tech_info")&&(A.document.getElementById("numeric_code").textContent=String(a));if(G[23]&&A.document.getElementById(ea)){var e=A.document.getElementById(ea);
Fa()||e.classList.add("unsupported_browser_show")}}));return new Promise(y())},jb=function(a,b,c){b=b===void 0?"":b;var d,e=(d=A.GLOBALS)!=null?d:[];d=A.performance&&A.performance.getEntries().find(function(h){return h instanceof A.PerformanceResourceTiming&&h.initiatorType=="iframe"&&/.+\/mail(\/u\/\d+)?\/data(\?|$)/.test(h.name)});Sa(aa,{error_page_cause:a,window_type:Va(),mct:e[109],error:b+(c&&c.stack?"\n"+c.stack:""),debug:JSON.stringify({userAgent:e[71],build:e[3],jsVersion:e[4],inboxType:e[65],
navPreloadHtml:e[79],offlineEnabled:e[61],reloadCount:A.sessionStorage.getItem("reload_count"),isCacheableHtml:e[57],dataIframe:!!d,dataIframePath:A.GM_DIP||null,dataIframeLocationError:A.GM_DILE||null,dataIframeReadyState:A.GM_DIRS||null,staleFlagError:A.GM_SFE||null,isChat:e[102]})})},lb=function(a){if(A.GM_LC)throw a;kb(9,"Uncaught exception",a)},ob=function(a){var b=!!G[6][2];if(!a){if(b&&G[14])return J(K,"C"),2;J(K,"D");return 1}var c=a.split("/"),d=c[0]==="chat";if(b){b=c.length===2;if(c[1]===
"home"&&b&&d||a==="onboarding"||mb.exec(a))return 2;a=c[1];if((a==="mentions"||a==="starred")&&b&&d)return 4}if(!d)return J(K,"E"),1;a=!!G[6][3];d=c[3]==="management";a=c[1]==="join"&&a;if(!(a?c.length===4:d?c.length>=3:c.length>=3&&c.length<=5))return J(K,"F`"+c.length),1;var e=a?2:1;b=a?3:2;if(c[e]!=="space"&&c[e]!=="dm"&&(!G[6][4]||c[1]!=="newdm"&&c[1]!=="startdm"))return L(K,"G"),1;e=c[1]==="newdm";if((c[1]==="startdm"||e)&&c.length===3)return 3;e=RegExp("^[A-Za-z0-9=_-]{11,12}$");if(c[1]!=="newdm"&&
c[1]!=="startdm"&&!e.test(c[b]))return L(K,"H"),1;try{nb(c[b])}catch(h){return L(K,"I"),1}if(a||c.length===3||d)return 3;if(!e.test(c[3]))return L(K,"J"),1;try{nb(c[3])}catch(h){return L(K,"K"),1}if(c.length===4)return 3;if(!e.test(c[4]))return L(K,"L"),1;try{nb(c[4])}catch(h){return L(K,"M"),1}return 3},nb=function(a){atob(a.replaceAll("_","/").replaceAll("-","+"))},sb=function(a,b,c){return new Promise(function(d,e){var h=pb(a,b);h.async=!1;h.addEventListener(v,function(){qb(b);d(c)});h.addEventListener(q,
function(f){e(Error("P`"+h.src,{cause:f.error}));rb(f,h)});A.document.body.appendChild(h)})},wb=function(a,b,c,d){return new Promise(function(e,h){A[d]=function(r){qb(b);delete A[d];p.removeEventListener(q,k);p.removeEventListener(v,m);e(c.then(function(){try{r.call(A,tb)}catch(t){throw lb(t),t;}}))};var f=0,g=function(){return f<ub.length?(setTimeout(function(){var r=p;p=n();document.body.insertBefore(p,r);document.body.removeChild(r)},ub[f]),f++,!0):!1},k=function(r){g()||(h(Error("Q`"+p.src,{cause:r.error})),
rb(r,p))},m=function(r){if(!g()){var t="Script "+p.id+" loaded but did not execute: "+p.src;h(Error("R`"+t,{cause:r}));kb(4,t+" ("+vb(p.src)+")")}},n=function(){var r=pb(a,b);r.async=!1;r.addEventListener(q,k);r.addEventListener(v,m);return r},p=n();document.body.appendChild(p)})},pb=function(a,b){var c=xb("SCRIPT");c.src=oa(a);var d;a=c.ownerDocument&&c.ownerDocument.defaultView||window;a=a===void 0?document:a;var e;a=(e=(d="document"in a?a.document:a).querySelector)==null?void 0:e.call(d,"script[nonce]");
(d=a==null?"":a.nonce||a.getAttribute("nonce")||"")&&c.setAttribute("nonce",d);c.id="base-js-"+b;return c},qb=function(a){A["GM_TRACING_SCRIPT_"+a+"_PARSE_DONE"]=A.performance?A.performance.now():null},rb=function(a,b){var c=b.src,d=vb(c);kb(4,"Failed to load script "+b.id+": "+c+" ("+d+")",a&&a.error)},vb=function(a){if(!A.performance)return"performance API unavailable";try{var b=A.performance.getEntriesByName(a,"resource").pop();if(!b)return"no performance entry found";var c=b.startTime,d=[b.redirectStart,
b.redirectEnd,b.fetchStart,b.domainLookupStart,b.domainLookupEnd,b.connectStart,b.secureConnectionStart,b.connectEnd,b.requestStart,b.responseStart,b.responseEnd].map(function(e){if(!e)return"";var h=Math.round(e-c);c=e;return h}).join("-");return"size: "+b.transferSize+", body: "+b.encodedBodySize+", duration: "+(b.duration+" ("+d+"), protocol: ")+(b.nextHopProtocol+", worker: "+b.workerStart)}catch(e){return"performance API exception: "+e}},yb=function(a){var b=0;return function(){return b<a.length?
{done:!1,value:a[b++]}:{done:!0}}},zb=typeof Object.defineProperties==u?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a},Ab=function(a){a=[w==typeof globalThis&&globalThis,a,w==typeof window&&window,w==typeof self&&self,w==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("a");},M=Ab(this),N=function(a,b){if(b)a:{var c=M;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in
c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&b!=null&&zb(c,a,{configurable:!0,writable:!0,value:b})}};N("Symbol",function(a){if(a)return a;var b=function(h,f){this.g=h;zb(this,"description",{configurable:!0,writable:!0,value:f})};b.prototype.toString=function(){return this.g};var c="jscomp_symbol_"+(Math.random()*1E9>>>0)+"_",d=0,e=function(h){if(this instanceof e)throw new TypeError("b");return new b(c+(h||"")+"_"+d++,h)};return e});
N("Symbol.iterator",function(a){if(a)return a;a=Symbol("c");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=M[b[c]];typeof d===u&&typeof d.prototype[a]!=u&&zb(d.prototype,a,{configurable:!0,writable:!0,value:function(){return Bb(yb(this))}})}return a});
var Bb=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a},Cb=typeof Object.create==u?Object.create:function(a){var b=y();b.prototype=a;return new b},Db;if(typeof Object.setPrototypeOf==u)Db=Object.setPrototypeOf;else{var Eb;a:{var Fb={a:!0},Gb={};try{Gb.__proto__=Fb;Eb=Gb.a;break a}catch(a){}Eb=!1}Db=Eb?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError("d`"+a);return a}:null}
var Hb=Db,O=function(a,b){a.prototype=Cb(b.prototype);a.prototype.constructor=a;if(Hb)Hb(a,b);else for(var c in b)if(c!="prototype")if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.X=b.prototype},P=function(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return{next:yb(a)};throw Error("e`"+String(a));};
N("Promise",function(a){function b(){this.g=null}function c(f){return f instanceof e?f:new e(function(g){g(f)})}if(a)return a;b.prototype.i=function(f){if(this.g==null){this.g=[];var g=this;this.j(function(){g.m()})}this.g.push(f)};var d=M.setTimeout;b.prototype.j=function(f){d(f,0)};b.prototype.m=function(){for(;this.g&&this.g.length;){var f=this.g;this.g=[];for(var g=0;g<f.length;++g){var k=f[g];f[g]=null;try{k()}catch(m){this.l(m)}}}this.g=null};b.prototype.l=function(f){this.j(function(){throw f;
})};var e=function(f){this.g=0;this.j=void 0;this.i=[];this.v=!1;var g=this.l();try{f(g.resolve,g.reject)}catch(k){g.reject(k)}};e.prototype.l=function(){function f(m){return function(n){k||(k=!0,m.call(g,n))}}var g=this,k=!1;return{resolve:f(this.L),reject:f(this.m)}};e.prototype.L=function(f){if(f===this)this.m(new TypeError("f"));else if(f instanceof e)this.N(f);else{a:switch(typeof f){case w:var g=f!=null;break a;case u:g=!0;break a;default:g=!1}g?this.K(f):this.o(f)}};e.prototype.K=function(f){var g=
void 0;try{g=f.then}catch(k){this.m(k);return}typeof g==u?this.O(g,f):this.o(f)};e.prototype.m=function(f){this.A(2,f)};e.prototype.o=function(f){this.A(1,f)};e.prototype.A=function(f,g){if(this.g!=0)throw Error("g`"+f+"`"+g+"`"+this.g);this.g=f;this.j=g;this.g===2&&this.M();this.I()};e.prototype.M=function(){var f=this;d(function(){if(f.J()){var g=M.console;typeof g!=="undefined"&&g.error(f.j)}},1)};e.prototype.J=function(){if(this.v)return!1;var f=M.CustomEvent,g=M.Event,k=M.dispatchEvent;if(typeof k===
"undefined")return!0;typeof f===u?f=new f(ca,{cancelable:!0}):typeof g===u?f=new g(ca,{cancelable:!0}):(f=M.document.createEvent("CustomEvent"),f.initCustomEvent(ca,!1,!0,f));f.promise=this;f.reason=this.j;return k(f)};e.prototype.I=function(){if(this.i!=null){for(var f=0;f<this.i.length;++f)h.i(this.i[f]);this.i=null}};var h=new b;e.prototype.N=function(f){var g=this.l();f.D(g.resolve,g.reject)};e.prototype.O=function(f,g){var k=this.l();try{f.call(g,k.resolve,k.reject)}catch(m){k.reject(m)}};e.prototype.then=
function(f,g){function k(r,t){return typeof r==u?function(E){try{m(r(E))}catch(F){n(F)}}:t}var m,n,p=new e(function(r,t){m=r;n=t});this.D(k(f,m),k(g,n));return p};e.prototype.catch=function(f){return this.then(void 0,f)};e.prototype.D=function(f,g){function k(){switch(m.g){case 1:f(m.j);break;case 2:g(m.j);break;default:throw Error("h`"+m.g);}}var m=this;this.i==null?h.i(k):this.i.push(k);this.v=!0};e.resolve=c;e.reject=function(f){return new e(function(g,k){k(f)})};e.race=function(f){return new e(function(g,
k){for(var m=P(f),n=m.next();!n.done;n=m.next())c(n.value).D(g,k)})};e.all=function(f){var g=P(f),k=g.next();return k.done?c([]):new e(function(m,n){function p(E){return function(F){r[E]=F;t--;t==0&&m(r)}}var r=[],t=0;do r.push(void 0),t++,c(k.value).D(p(r.length-1),n),k=g.next();while(!k.done)})};return e});
N("String.prototype.startsWith",function(a){return a?a:function(b,c){if(this==null)throw new TypeError("i`startsWith");if(b instanceof RegExp)throw new TypeError("j`startsWith");var d=this.length,e=b.length;c=Math.max(0,Math.min(c|0,this.length));for(var h=0;h<e&&c<d;)if(this[c++]!=b[h++])return!1;return h>=e}});var R=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};N("Symbol.dispose",function(a){return a?a:Symbol("k")});N("globalThis",function(a){return a||M});
N("WeakMap",function(a){function b(){}function c(k){var m=typeof k;return m===w&&k!==null||m===u}function d(k){if(!R(k,h)){var m=new b;zb(k,h,{value:m})}}function e(k){var m=Object[k];m&&(Object[k]=function(n){if(n instanceof b)return n;Object.isExtensible(n)&&d(n);return m(n)})}if(function(){if(!a||!Object.seal)return!1;try{var k=Object.seal({}),m=Object.seal({}),n=new a([[k,2],[m,3]]);if(n.get(k)!=2||n.get(m)!=3)return!1;n.delete(k);n.set(m,4);return!n.has(k)&&n.get(m)==4}catch(p){return!1}}())return a;
var h="$jscomp_hidden_"+Math.random();e("freeze");e("preventExtensions");e("seal");var f=0,g=function(k){this.g=(f+=Math.random()+1).toString();if(k){k=P(k);for(var m;!(m=k.next()).done;)m=m.value,this.set(m[0],m[1])}};g.prototype.set=function(k,m){if(!c(k))throw Error("l");d(k);if(!R(k,h))throw Error("m`"+k);k[h][this.g]=m;return this};g.prototype.get=function(k){return c(k)&&R(k,h)?k[h][this.g]:void 0};g.prototype.has=function(k){return c(k)&&R(k,h)&&R(k[h],this.g)};g.prototype.delete=function(k){return c(k)&&
R(k,h)&&R(k[h],this.g)?delete k[h][this.g]:!1};return g});
N("Map",function(a){if(function(){if(!a||typeof a!=u||!a.prototype.entries||typeof Object.seal!=u)return!1;try{var g=Object.seal({x:4}),k=new a(P([[g,"s"]]));if(k.get(g)!="s"||k.size!=1||k.get({x:4})||k.set({x:4},"t")!=k||k.size!=2)return!1;var m=k.entries(),n=m.next();if(n.done||n.value[0]!=g||n.value[1]!="s")return!1;n=m.next();return n.done||n.value[0].x!=4||n.value[1]!="t"||!m.next().done?!1:!0}catch(p){return!1}}())return a;var b=new WeakMap,c=function(g){this[0]={};this[1]=h();this.size=0;if(g){g=
P(g);for(var k;!(k=g.next()).done;)k=k.value,this.set(k[0],k[1])}};c.prototype.set=function(g,k){g=g===0?0:g;var m=d(this,g);m.list||(m.list=this[0][m.id]=[]);m.u?m.u.value=k:(m.u={next:this[1],B:this[1].B,head:this[1],key:g,value:k},m.list.push(m.u),this[1].B.next=m.u,this[1].B=m.u,this.size++);return this};c.prototype.delete=function(g){g=d(this,g);return g.u&&g.list?(g.list.splice(g.index,1),g.list.length||delete this[0][g.id],g.u.B.next=g.u.next,g.u.next.B=g.u.B,g.u.head=null,this.size--,!0):
!1};c.prototype.clear=function(){this[0]={};this[1]=this[1].B=h();this.size=0};c.prototype.has=function(g){return!!d(this,g).u};c.prototype.get=function(g){return(g=d(this,g).u)&&g.value};c.prototype.entries=function(){return e(this,function(g){return[g.key,g.value]})};c.prototype.keys=function(){return e(this,function(g){return g.key})};c.prototype.values=function(){return e(this,function(g){return g.value})};c.prototype.forEach=function(g,k){for(var m=this.entries(),n;!(n=m.next()).done;)n=n.value,
g.call(k,n[1],n[0],this)};c.prototype[Symbol.iterator]=c.prototype.entries;var d=function(g,k){var m=k&&typeof k;m==w||m==u?b.has(k)?m=b.get(k):(m=""+ ++f,b.set(k,m)):m="p_"+k;var n=g[0][m];if(n&&R(g[0],m))for(g=0;g<n.length;g++){var p=n[g];if(k!==k&&p.key!==p.key||k===p.key)return{id:m,list:n,index:g,u:p}}return{id:m,list:n,index:-1,u:void 0}},e=function(g,k){var m=g[1];return Bb(function(){if(m){for(;m.head!=g[1];)m=m.B;for(;m.next!=m.head;)return m=m.next,{done:!1,value:k(m)};m=null}return{done:!0,
value:void 0}})},h=function(){var g={};return g.B=g.next=g.head=g},f=0;return c});
N("Set",function(a){if(function(){if(!a||typeof a!=u||!a.prototype.entries||typeof Object.seal!=u)return!1;try{var c=Object.seal({x:4}),d=new a(P([c]));if(!d.has(c)||d.size!=1||d.add(c)!=d||d.size!=1||d.add({x:4})!=d||d.size!=2)return!1;var e=d.entries(),h=e.next();if(h.done||h.value[0]!=c||h.value[1]!=c)return!1;h=e.next();return h.done||h.value[0]==c||h.value[0].x!=4||h.value[1]!=h.value[0]?!1:e.next().done}catch(f){return!1}}())return a;var b=function(c){this.g=new Map;if(c){c=P(c);for(var d;!(d=
c.next()).done;)this.add(d.value)}this.size=this.g.size};b.prototype.add=function(c){c=c===0?0:c;this.g.set(c,c);this.size=this.g.size;return this};b.prototype.delete=function(c){c=this.g.delete(c);this.size=this.g.size;return c};b.prototype.clear=function(){this.g.clear();this.size=0};b.prototype.has=function(c){return this.g.has(c)};b.prototype.entries=function(){return this.g.entries()};b.prototype.values=function(){return this.g.values()};b.prototype.keys=b.prototype.values;b.prototype[Symbol.iterator]=
b.prototype.values;b.prototype.forEach=function(c,d){var e=this;this.g.forEach(function(h){return c.call(d,h,h,e)})};return b});var Ib=function(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var h=c++;return{value:b(h,a[h]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e};N("Array.prototype.entries",function(a){return a?a:function(){return Ib(this,function(b,c){return[b,c]})}});
N("Array.prototype.keys",function(a){return a?a:function(){return Ib(this,fa())}});N("Array.prototype.find",function(a){return a?a:function(b,c){a:{var d=this;d instanceof String&&(d=String(d));for(var e=d.length,h=0;h<e;h++){var f=d[h];if(b.call(c,f,h,d)){b=f;break a}}b=void 0}return b}});N("Array.prototype.values",function(a){return a?a:function(){return Ib(this,function(b,c){return c})}});
N("Array.from",function(a){return a?a:function(b,c,d){c=c!=null?c:fa();var e=[],h=typeof Symbol!="undefined"&&Symbol.iterator&&b[Symbol.iterator];if(typeof h==u){b=h.call(b);for(var f=0;!(h=b.next()).done;)e.push(c.call(d,h.value,f++))}else for(h=b.length,f=0;f<h;f++)e.push(c.call(d,b[f],f));return e}});
N("String.prototype.replaceAll",function(a){return a?a:function(b,c){if(b instanceof RegExp&&!b.global)throw new TypeError("n");return b instanceof RegExp?this.replace(b,c):this.replace(new RegExp(String(b).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08"),"g"),c)}});N("Object.entries",function(a){return a?a:function(b){var c=[],d;for(d in b)R(b,d)&&c.push([d,b[d]]);return c}});var A=this||self,S=function(a,b,c){a=a.split(".");c=c||A;a[0]in c||typeof c.execScript=="undefined"||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||b===void 0?c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}:c[d]=b},Jb=A._F_toggles||[];var ib=function(){this.g=encodeURIComponent("gmail")},hb=function(a,b){var c=[];c.push("s="+a.g);c.push("a="+encodeURIComponent(aa));c.push("c="+encodeURIComponent(b));a="//clients2.google.com/availability/?"+c.join("&");a=a+"&tm="+(new Date).getTime();a=a+"&zx="+Math.random();(new Image).src=a};var Kb=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]},xa=function(a,b){var c=0;a=Kb(String(a)).split(".");b=Kb(String(b)).split(".");for(var d=Math.max(a.length,b.length),e=0;c==0&&e<d;e++){var h=a[e]||"",f=b[e]||"";do{h=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];f=/(\d*)(\D*)(.*)/.exec(f)||["","","",""];if(h[0].length==0&&f[0].length==0)break;c=Lb(h[1].length==0?0:parseInt(h[1],10),f[1].length==0?0:parseInt(f[1],10))||Lb(h[2].length==
0,f[2].length==0)||Lb(h[2],f[2]);h=h[3];f=f[3]}while(c==0)}return c},Lb=function(a,b){return a<b?-1:a>b?1:0};var ia=globalThis.trustedTypes,ka;var ma=ha("g");ma.prototype.toString=function(){return this.g+""};var Mb=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if(typeof a===x)return typeof b!==x||b.length!=1?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Nb=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=typeof a===x?a.split(""):a,h=0;h<d;h++)h in e&&b.call(c,e[h],h,a)};var Ob=function(a,b){this.name=a;this.value=b};Ob.prototype.toString=function(){return this.name};var Za=new Ob("OFF",Infinity),Ra=new Ob("SEVERE",1E3),Pb=new Ob("WARNING",900),Qb=new Ob("INFO",800),Rb=new Ob("CONFIG",700),Xa=y(),Wa,Ya=function(a,b,c){this.reset(a||Za,b,c,void 0,void 0)};Ya.prototype.reset=ha("g");
var Sb=function(a,b){this.g=null;this.l=[];this.i=(b===void 0?null:b)||null;this.j=[];this.m={g:function(){return a}}},Tb=function(a){return a.g?a.g:a.i?Tb(a.i):Za},ab=function(a,b){for(;a;)a.l.forEach(function(c){c(b)}),a=a.i},Ub=function(){this.entries={};var a=new Sb("");a.g=Rb;this.entries[""]=a},Vb,bb=function(a,b){var c=a.entries[b];if(c)return c;c=bb(a,b.slice(0,Math.max(b.lastIndexOf("."),0)));var d=new Sb(b,c);a.entries[b]=d;c.j.push(d);return d},cb=function(){Vb||(Vb=new Ub);return Vb},
Wb=function(a){return bb(cb(),a).m},$a=function(a){return a?Tb(bb(cb(),a.g())):Za},Qa=function(a,b,c){if(a&&a&&b&&b.value>=$a(a).value){b=b||Za;var d=bb(cb(),a.g());typeof c===u&&(c=c());Wa||(Wa=new Xa);a=new Ya(b,c,a.g());ab(d,a)}},L=function(a,b){a&&Qa(a,Pb,b)},J=function(a,b){a&&Qa(a,Qb,b)};Math.floor(Math.random()*2147483648).toString(36);Math.abs(Math.floor(Math.random()*2147483648)^Date.now()).toString(36);var Xb=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^\\\\/?#]*)@)?([^\\\\/?#]*?)(?::([0-9]+))?(?=[\\\\/?#]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#([\\s\\S]*))?$"),Yb=function(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e=null;if(d>=0){var h=a[c].substring(0,d);e=a[c].substring(d+1)}else h=a[c];b(h,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}},Zb=function(a,b,c){if(Array.isArray(b))for(var d=0;d<b.length;d++)Zb(a,String(b[d]),c);else b!=null&&c.push(a+(b===""?"":"="+encodeURIComponent(String(b))))},
Oa=function(a){var b=[],c;for(c in a)Zb(c,a[c],b);return b.join("&")},$b=function(a,b,c,d){for(var e=c.length;(b=a.indexOf(c,b))>=0&&b<d;){var h=a.charCodeAt(b-1);if(h==38||h==63)if(h=a.charCodeAt(b+e),!h||h==61||h==38||h==35)return b;b+=e+1}return-1},ac=/#|$/,Ua=function(a,b){var c=a.search(ac),d=$b(a,0,b,c);if(d<0)return null;var e=a.indexOf("&",d);if(e<0||e>c)e=c;d+=b.length+1;return decodeURIComponent(a.slice(d,e!==-1?e:0).replace(/\+/g," "))};var Ta;var bc=/[\/;]+k=(.[^\/]*)/,cc,Ka=function(){if(cc!==void 0)return cc;if(A.___jsl&&A.___jsl.h){var a=bc.exec(A.___jsl.h);return cc=a&&a[1]||null}return cc=null};var G=A.GM_BOOTSTRAP_DATA;var dc=!!(Jb[0]&2048);var ec;if(Jb[0]&1024)ec=dc;else{var fc;a:{for(var gc=["WIZ_global_data","oxN3nb"],hc=A,ic=0;ic<gc.length;ic++)if(hc=hc[gc[ic]],hc==null){fc=null;break a}fc=hc}var jc=fc&&fc[610401301];ec=jc!=null?jc:!1}var qa=ec;var B,kc=A.navigator;B=kc?kc.userAgentData||null:null;var mc=function(a,b){var c=lc;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var Ea=sa(),Aa=D()?!1:C("Trident")||C("MSIE"),Da=C(l),Ba=C("Gecko")&&!(pa().toLowerCase().indexOf("webkit")!=-1&&!C(l))&&!(C("Trident")||C("MSIE"))&&!C(l),nc=pa().toLowerCase().indexOf("webkit")!=-1&&!C(l),oc;
a:{var pc="",qc=function(){var a=pa();if(Ba)return/rv:([^\);]+)(\)|;)/.exec(a);if(Da)return/Edge\/([\d\.]+)/.exec(a);if(Aa)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(nc)return/WebKit\/(\S+)/.exec(a);if(Ea)return/(?:Version)[ \/]?(\S+)/.exec(a)}();qc&&(pc=qc?qc[1]:"");if(Aa){var rc,tc=A.document;rc=tc?tc.documentMode:void 0;if(rc!=null&&rc>parseFloat(pc)){oc=String(rc);break a}}oc=pc}var uc=oc,lc={},Ca=function(a){return mc(a,function(){return xa(uc,a)>=0})};var vc=ta(),wc=va()||C("iPod"),xc=C("iPad"),yc=C("Android")&&!(ua()||ta()||sa()||C("Silk")),wa=ua(),za=C("Safari")&&!(ua()||(D()?0:C("Coast"))||sa()||(D()?0:C(l))||(D()?ra("Microsoft Edge"):C("Edg/"))||(D()?ra("Opera"):C("OPR"))||ta()||C("Silk")||C("Android"))&&!(va()||C("iPad")||C("iPod"));var zc=function(a){return(a=a.exec(pa()))?a[1]:""},ya=function(){if(vc)return zc(/Firefox\/([0-9.]+)/);if(Aa||Da||Ea)return uc;if(wa){if(va()||C("iPad")||C("iPod")||(qa&&B&&B.platform?B.platform==="macOS":C("Macintosh"))){var a=zc(/CriOS\/([0-9.]+)/);if(a)return a}return zc(/Chrome\/([0-9.]+)/)}if(za&&!(va()||C("iPad")||C("iPod")))return zc(/Version\/([0-9.]+)/);if(wc||xc){if(a=/Version\/(\S+).*Mobile\/(\S+)/.exec(pa()))return a[1]+"."+a[2]}else if(yc)return(a=zc(/Android\s+([0-9.]+)/))?a:zc(/Version\/([0-9.]+)/);
return""}();var Ga=/\/mail(\/ca)?\/b\/[^\/]+\/u\/[^\/]+/,Ia=/\/mail\/u\/[^\/]+\/d\/[^\/]+/,Ha=/\/a\/[^\/]+\/b\/[^\/]+\/u\/[^\/]+/;var H=function(a){this.i=this.v=this.m="";this.A=null;this.l=this.j="";this.o=!1;var b;a instanceof H?(this.o=a.o,Ac(this,a.m),this.v=a.v,this.i=a.i,Bc(this,a.A),Ma(this,a.j),Na(this,Cc(a.g)),this.l=a.l):a&&(b=String(a).match(Xb))?(this.o=!1,Ac(this,b[1]||"",!0),this.v=Dc(b[2]||""),this.i=Dc(b[3]||"",!0),Bc(this,b[4]),Ma(this,b[5]||"",!0),Na(this,b[6]||"",!0),this.l=Dc(b[7]||"")):(this.o=!1,this.g=new T(null,this.o))};
H.prototype.toString=function(){var a=[],b=this.m;b&&a.push(Ec(b,Fc,!0),":");var c=this.i;if(c||b=="file")a.push("//"),(b=this.v)&&a.push(Ec(b,Fc,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.A,c!=null&&a.push(":",String(c));if(c=this.j)this.i&&c.charAt(0)!="/"&&a.push("/"),a.push(Ec(c,c.charAt(0)=="/"?Gc:Hc,!0));(c=this.g.toString())&&a.push("?",c);(c=this.l)&&a.push("#",Ec(c,Ic));return a.join("")};
H.prototype.resolve=function(a){var b=new H(this),c=!!a.m;c?Ac(b,a.m):c=!!a.v;c?b.v=a.v:c=!!a.i;c?b.i=a.i:c=a.A!=null;var d=a.j;if(c)Bc(b,a.A);else if(c=!!a.j){if(d.charAt(0)!="/")if(this.i&&!this.j)d="/"+d;else{var e=b.j.lastIndexOf("/");e!=-1&&(d=b.j.slice(0,e+1)+d)}e=d;if(e==".."||e==".")d="";else if(e.indexOf("./")!=-1||e.indexOf("/.")!=-1){d=e.lastIndexOf("/",0)==0;e=e.split("/");for(var h=[],f=0;f<e.length;){var g=e[f++];g=="."?d&&f==e.length&&h.push(""):g==".."?((h.length>1||h.length==1&&h[0]!=
"")&&h.pop(),d&&f==e.length&&h.push("")):(h.push(g),d=!0)}d=h.join("/")}else d=e}c?Ma(b,d):c=a.g.toString()!=="";c?Na(b,Cc(a.g)):c=!!a.l;c&&(b.l=a.l);return b};
var Ac=function(a,b,c){a.m=c?Dc(b,!0):b;a.m&&(a.m=a.m.replace(/:$/,""))},Bc=function(a,b){if(b){b=Number(b);if(isNaN(b)||b<0)throw Error("p`"+b);a.A=b}else a.A=null},Ma=function(a,b,c){a.j=c?Dc(b,!0):b},Na=function(a,b,c){b instanceof T?(a.g=b,Jc(a.g,a.o)):(c||(b=Ec(b,Kc)),a.g=new T(b,a.o))},Dc=function(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""},Ec=function(a,b,c){return typeof a===x?(a=encodeURI(a).replace(b,Lc),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):
null},Lc=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)},Fc=/[#\/\?@]/g,Hc=/[#\?:]/g,Gc=/[#\?]/g,Kc=/[#\?@]/g,Ic=/#/g,T=function(a,b){this.i=this.g=null;this.j=a||null;this.l=!!b},U=function(a){a.g||(a.g=new Map,a.i=0,a.j&&Yb(a.j,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))};T.prototype.add=function(a,b){U(this);this.j=null;a=Mc(this,a);var c=this.g.get(a);c||this.g.set(a,c=[]);c.push(b);this.i+=1;return this};
var Nc=function(a,b){U(a);b=Mc(a,b);a.g.has(b)&&(a.j=null,a.i-=a.g.get(b).length,a.g.delete(b))},Oc=function(a,b){U(a);b=Mc(a,b);return a.g.has(b)};T.prototype.forEach=function(a,b){U(this);this.g.forEach(function(c,d){c.forEach(function(e){a.call(b,e,d,this)},this)},this)};var Pc=function(a,b){U(a);var c=[];if(typeof b===x)Oc(a,b)&&(c=c.concat(a.g.get(Mc(a,b))));else for(a=Array.from(a.g.values()),b=0;b<a.length;b++)c=c.concat(a[b]);return c};
T.prototype.set=function(a,b){U(this);this.j=null;a=Mc(this,a);Oc(this,a)&&(this.i-=this.g.get(a).length);this.g.set(a,[b]);this.i+=1;return this};T.prototype.get=function(a,b){if(!a)return b;a=Pc(this,a);return a.length>0?String(a[0]):b};
T.prototype.toString=function(){if(this.j)return this.j;if(!this.g)return"";for(var a=[],b=Array.from(this.g.keys()),c=0;c<b.length;c++){var d=b[c],e=encodeURIComponent(String(d));d=Pc(this,d);for(var h=0;h<d.length;h++){var f=e;d[h]!==""&&(f+="="+encodeURIComponent(String(d[h])));a.push(f)}}return this.j=a.join("&")};
var Cc=function(a){var b=new T;b.j=a.j;a.g&&(b.g=new Map(a.g),b.i=a.i);return b},Mc=function(a,b){b=String(b);a.l&&(b=b.toLowerCase());return b},Jc=function(a,b){b&&!a.l&&(U(a),a.j=null,a.g.forEach(function(c,d){var e=d.toLowerCase();if(d!=e&&(Nc(this,d),Nc(this,e),c.length>0)){this.j=null;d=this.g;var h=d.set;e=Mc(this,e);var f=c.length;if(f>0){for(var g=Array(f),k=0;k<f;k++)g[k]=c[k];f=g}else f=[];h.call(d,e,f);this.i+=c.length}},a));a.l=b};var Pa=Wb("r");var Qc=function(){this.i=this.i;this.m=this.m};Qc.prototype.i=!1;Qc.prototype.dispose=function(){if(!this.i&&(this.i=!0,this.m))for(;this.m.length;)this.m.shift()()};Qc.prototype[Symbol.dispose]=function(){this.dispose()};var Rc=function(){Qc.call(this);this.o=0;this.l=this.g=null};O(Rc,Qc);Rc.prototype.j=Wb("z");var I=new Rc,db=function(a,b,c){this.i=a;this.e=b;this.g=c};var gb=Wb("A");A.GM_REP=A.GM_REP||new Set;A.GM_DEP=A.GM_DEP===void 0?null:A.GM_DEP;var fb=A.GM_REP;var K=Wb("B"),mb=/\/welcome$/,Sc=!1;S("_GM_parseLoadToView",function(){if(!Sc){Sc=!0;var a=(new H(A.top.location.href)).l;switch(ob(a)){case 2:A._GM_loadToViewInfo="chat/home";break;case 4:A._GM_loadToViewInfo=a;break;case 3:A._GM_loadToViewInfo=a;A._GM_loadToStreamInfoExists=!0;break;case 1:J(K,"N");break;default:K&&Qa(K,Ra,"O")}}});S("_GM_loadToViewInfo","");S("_GM_loadToStreamInfoExists",!1);var tb={};var xb=function(a){var b=document;a=String(a);b.contentType==="application/xhtml+xml"&&(a=a.toLowerCase());return b.createElement(a)};var ub=[0,100,1E3];S("_GM_loadJS",function(){var a=A.GM_JS_URLS;if(!a)throw Error("S");a=a.map(function(c){return na(c)});var b=Promise.resolve();a.forEach(function(c,d){d+=1;var e=/\/cb=(loaded_\d+)(?:\/|$)/.exec(c.toString());b=e?wb(c,d,b,e[1]):sb(c,d,b)});return b.then(function(){A._B_init(A);A._jsl=!0;A.MAIN_JS_EXECUTION_END_TIME=A.performance?A.performance.now():null})});
}catch(e){_DumpException(e)}
try{
var Tc="(any-pointer:coarse)",Uc="(pointer:coarse)",Vc="?compose=",Wc='Unknown Error of type "',Xc="_DumpException",Yc="embedded_data_iframe",Zc="gtn-brain-iframe-id",$c="jscookietest=valid",ad="navigation_type",bd="navigation_type_timestamp",dd=function(){return cd(function(a){return a()})?!1:!G[14]&&G[15]===3&&wa&&xa(ya,84)>=0},gd=function(a){var b=b===void 0?{}:b;var c=b.V===void 0?ed:b.V,d=b.T===void 0?y():b.T,e=function(h){return fetch(a.clone()).then(function(f){h>0&&J(fd,"U`"+a.url+"`"+h+"`1");
return f},function(f){L(fd,"V`"+a.url+"`"+h+"`1");if(h<c.length){d(f);var g=c[h];return(new Promise(function(k){setTimeout(k,g)})).then(function(){return e(h+1)})}L(fd,"W`"+a.url+"`"+h+"`1");throw f;})};e(0)},id=function(a){if(!hd(a))return a;try{var b=atob;for(var c=!0,d=a.length,e=0;e<d;e++)if(a.charAt(e)!="B"){c=!1;break}if(c)var h="A";else{d={};for(c=0;c<40;c++)d["BCDFGHJKLMNPQRSTVWXZbcdfghjklmnpqrstvwxz".charAt(c)]=c;c=[];for(var f=a.length-1;f>=0;f--){var g=a.charAt(f),k=d[g];if(typeof k=="undefined")throw Error("Y`"+
a+"`BCDFGHJKLMNPQRSTVWXZbcdfghjklmnpqrstvwxz`"+g);c.push(k)}f=[];for(var m=c.length-1;m>=0;m--){g=0;var n=f.length;for(k=0;k<n;k++){var p=f[k];p=p*40+g;p>=64?(d=p%64,g=(p-d)/64,p=d):g=0;f[k]=p}for(;g;)k=g%64,f.push(k),g=(g-k)/64;g=c[m];for(k=0;g;){k>=f.length&&f.push(0);var r=f[k];r+=g;r>=64?(d=r%64,g=(r-d)/64,r=d):g=0;f[k]=r;k++}}m=[];for(var t=f.length-1;t>=0;t--){var E=f[t];if(E>=64||E<0)throw Error("Z`"+f+"`"+E);m.push("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(E))}h=
m.join("")}}catch(F){return a}return b(h)},kd=function(a){var b=a.split(",");return jd(b[0])||!hd(a)?b:id(a).split(",").map(function(c){return c.startsWith("thread-")||c==="new"||c===""?c:"thread-"+c})},hd=function(a){return RegExp("^[BCDFGHJKLMNPQRSTVWXZbcdfghjklmnpqrstvwxz]*$").test(a)},jd=function(a){return a?a.indexOf("thread-")!=-1||a.indexOf("msg-")!=-1:!1},td=function(){var a=ld(),b=xb("IFRAME");a&&(b.src=oa(a).toString());b.id=Zc;b.name=Zc;b.className="wYWn3";b.style.position="absolute";b.style.top=
"0";b.style.left="0";b.style.width="0";b.style.height="0";b.style.border="0";b.allow="idle-detection; autoplay; clipboard-write;camera; microphone; cross-origin-isolated;";A.GM_CH_BFLP=new Promise(function(d,e){var h=function(){d();b.removeEventListener(q,f)},f=function(g){e(Error("ba",{cause:g}));b.removeEventListener(v,h)};b.addEventListener(v,h,{once:!0});b.addEventListener(q,f,{once:!0})});var c;A.GM_CH_PP=new Promise(function(d){c=d});a&&md({destination:window,S:b,origin:nd(a.toString()),F:"cc",
C:function(d){c(d.ports[0])}});document.body.appendChild(b);A.performance&&A.performance.mark&&A.performance.mark("gm_bf_it")},ud=function(a){try{var b=a.contentWindow.document.location.href=="about:blank"?"loading":a.contentWindow.document.readyState;A.GM_DIP=a.contentWindow.document.location.pathname;A.GM_DIRS=a.contentWindow.document.readyState;return b=="loading"}catch(c){return A.GM_DILE=c.toString(),!1}},vd=function(){var a;switch((a=performance.getEntriesByType("navigation").find(function(b){return b.name==
document.location.href}))==null?void 0:a.type){case "navigate":return 0;case "reload":return 1;case "back_forward":return 2;case "prerender":return 3;default:return-1}},wd=function(a,b,c){if(c==null)return b;if(typeof c===x)return c?a+encodeURIComponent(c):"";for(var d in c)if(Object.prototype.hasOwnProperty.call(c,d)){var e=c[d];e=Array.isArray(e)?e:[e];for(var h=0;h<e.length;h++){var f=e[h];f!=null&&(b||(b=a),b+=(b.length>a.length?"&":"")+encodeURIComponent(d)+"="+encodeURIComponent(String(f)))}}return b},
ld=function(){if(xd!==null)return xd;var a=na(G[13]),b={};try{var c;(c=A._GM_parseLoadToView)==null||c.call(A);if(A._GM_loadToViewInfo){b.lts=A._GM_loadToViewInfo;var d=(new URL(window.location.href)).searchParams.get("cls");d&&(b.cls=d)}}catch(h){}if(G[14]){var e=e===void 0?window:e;c=e.matchMedia("(display-mode: standalone), (display-mode: minimal-ui)").matches?10:9}else c=6;yd=c;b.shell=String(yd);b.has_stream_view=String(!!A._GM_loadToStreamInfoExists);b.origin=window.location.origin;dd()&&(b.oi=
"1");c={};c=(c.hot=A.performance.timing.navigationStart,c);a=oa(a);a=zd.exec(a);d=a[3]||"";return xd=na(a[1]+wd("?",a[2]||"",b)+wd("#",d,c))},Cd=function(a){if(!a)return"";a=a.split("/");return Mb(Ad,a[0])>=0||a.length==2&&Mb(Bd,a[0])>=0?"":a[a.length-1]},Gd=function(a){a=Cd(a);var b=Dd(a);return/^[\s\xa0]*$/.test(b)||!/^[0-9A-Fa-f]*$/.test(b)&&!Ed(b)?!1:Fd(a)},Fd=function(a){a=Dd(a);return a!="new"&&!Ed(a)},Ed=function(a){return jd(a)?!0:kd(a).some(function(b){return jd(b)})},Dd=function(a){var b=
a.split(Vc);return b.length>1?b[1]:a},Jd=function(){var a=V,b=X,c=Dd(Cd(b));if(!/^[\s\xa0]*$/.test(c)){var d=kd(c),e=d.some(function(h){return jd(h)});d=d.join(",");d!==c&&e&&(b=b.replace(c,d))}return Hd(Id(a,b))},Kd=function(a){if(!(a instanceof Array)){a=P(a);for(var b,c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a},Ld=function(a,b){a.raw=b;Object.freeze&&(Object.freeze(a),Object.freeze(b));return a},Md=function(a){return Ld(a,a)},Nd=function(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-
a]=arguments[c];return b},Od=/^\s*(?!javascript:)(?:[\w+.-]+:|[^:/?#]*(?:[/?#]|$))/i,Rd=function(){this.g=Pd?Pd.createScript(Qd):Qd};Rd.prototype.toString=function(){return this.g+""};
var nd=function(a){var b=a.match(Xb);a=b[1];var c=b[3];b=b[4];var d="";a&&(d+=a+":");c&&(d=d+"//"+c,b&&(d+=":"+b));return d},Hd=function(a){var b=a.indexOf("#");return b<0?a:a.slice(0,b)},Id=function(a,b){if(b="idr"+(b!=null?"="+encodeURIComponent(String(b)):"")){var c=a.indexOf("#");c<0&&(c=a.length);var d=a.indexOf("?");if(d<0||d>c){d=c;var e=""}else e=a.substring(d+1,c);a=[a.slice(0,d),e,a.slice(c)];c=a[1];a[1]=b?c?c+"&"+b:b:c;b=a[0]+(a[1]?"?"+a[1]:"")+a[2]}else b=a;return b},Sd=function(a){var b=
V;return $b(b,0,a,b.search(ac))>=0},Td=/[?&]($|#)/;var Ud=function(){this.g=[]},Xd=function(){return Vd.g.map(function(a){return Wd(a)})},Wd=function(a){var b=void 0;b=b===void 0?function(c){return new c}:b;return a.P?b(a.P):a.instance},Yd=function(){this.g=[]};O(Yd,Ud);var cd=function(a){var b=Xd();b=P(b);for(var c=b.next();!c.done;c=b.next())if(c=a(c.value))return c;return!1};var Vd=new Yd;var fd=Wb("T"),ed=[0,100,1E3,5E3,1E4,3E4,6E4];var Zd=Md(["return self;"]),Y=function(a,b){b=b===void 0?{}:b;var c=b.cause;var d=Error.call(this,a,c!==void 0?{cause:c}:void 0);this.message=d.message;"stack"in d&&(this.stack=d.stack);var e=b;b=e.fileName;d=e.lineNumber;var h=e.columnNumber,f=e.stack;e=e.name;try{this.columnNumber=h!=null?h:-1}catch(k){}try{this.message=a}catch(k){}try{b!=null?this.fileName=b:this.fileName||(this.fileName="Not available",this.fileName=A.$googDebugFname||window.location.href)}catch(k){}try{var g;this.lineNumber=
(g=d!=null?d:this.lineNumber)!=null?g:-1}catch(k){}try{this.stack=f!=null?f:this.stack||"Not available"}catch(k){}if(e!=null)try{this.name=e}catch(k){}try{this.cause!==c&&(this.cause=c)}catch(k){}};O(Y,Error);Y.prototype.name="ErrorToReport";var $d=function(){Y.apply(this,arguments)};O($d,Y);$d.prototype.name="UnknownEmptyError";var ae=function(){Y.apply(this,arguments)};O(ae,Y);ae.prototype.name="UnknownPrimitiveError";var be=function(){Y.apply(this,arguments)};O(be,Y);be.prototype.name="UnknownObjectError";
var ce=function(){Y.apply(this,arguments)};O(ce,Y);ce.prototype.name="WrappedError";var de;var ee,Qd=Zd.join(""),Pd=la();ee=new Rd;if(ee instanceof Rd)de=ee.g;else throw Error("o");
var fe=de,ge=function(a){try{if(a===A)return"";if(a){try{if(a.location)return"[global="+a.location.href+"]"}catch(b){}return"[global=unknown location]"}}catch(b){}return"[unknown global]"},he=function(a,b){try{var c=a.toString;if(c&&b&&c!==Object.prototype.toString&&c!==Array.prototype.toString&&(b===A||c!==b.Object.prototype.toString&&c!==b.Array.prototype.toString))return String(a)}catch(e){}try{var d=a.message;if(typeof d===x)return d}catch(e){}try{return JSON.stringify(a)}catch(e){}return null};var ie=function(a,b){b=b===void 0?{}:b;var c,d=(c=b.G)!=null?c:da;b=b===void 0?{}:b;c=b.fileName;var e=b.lineNumber,h=b.columnNumber,f;b=(f=b.message)!=null?f:null;f={fileName:c,lineNumber:e,columnNumber:h};f=f===void 0?{}:f;if(a===null||a===void 0){var g=f;g=g===void 0?{}:g;a=new $d(Wc+a+'"',{fileName:g.fileName,lineNumber:g.lineNumber,columnNumber:g.columnNumber})}else if(typeof a!==w)g=f,g=g===void 0?{}:g,a=new ae(Wc+typeof a+'": '+a,{fileName:g.fileName,lineNumber:g.lineNumber,columnNumber:g.columnNumber});
else if(a instanceof Error){g=f;var k=g=g===void 0?{}:g;g=k.fileName;var m=k.lineNumber;k=k.columnNumber;var n="Malformed Error";try{n=String(a.message)}catch(z){}if(!g)try{g=a.fileName||a.filename||a.sourceURL||void 0}catch(z){}if(m==null)try{m=a.lineNumber||a.line}catch(z){}if(k==null)try{k=a.columnNumber}catch(z){}try{var p=a.stack||void 0}catch(z){}try{var r=a.name||void 0}catch(z){}try{var t=a.cause}catch(z){}a=new ce(n,{fileName:g,lineNumber:m,columnNumber:k,stack:p,name:r,cause:t})}else{p=
f;t=p=p===void 0?{}:p;p=t.fileName;r=t.lineNumber;t=t.columnNumber;a:{try{var E=a.constructor;if(typeof E===u){var F=E;break a}}catch(z){}F=null}a:{try{if(!F){var La=null;break a}var W=F.constructor;if(typeof W===u){La=A.Function===W?A:(new W(fe))();break a}}catch(z){}La=null}a:{W=ge(La);try{if(F){try{var Q=F.name;if(typeof Q===x){n='"'+Q+W+'"';break a}}catch(z){}var od,pd=(od=/function\s+([^(\s]+)|class\s+([^{\s]+)/.exec(F))!=null?od:[],qd,rd=(qd=pd[1])!=null?qd:pd[2];if(rd!=null){n='"'+rd+W+'"';
break a}}}catch(z){}n=da+W}Q=he(a,La);n="Unknown Error of Object type "+n+(Q===null?", unable to stringify":Q.length>400?" ["+(Q.length-400)+" characters elided]: "+Q.substring(0,400)+"...":": "+Q);if(!p)try{p=a.fileName||a.filename||a.sourceURL||void 0}catch(z){}if(r==null)try{r=a.lineNumber||a.line}catch(z){}if(t==null)try{t=a.columnNumber}catch(z){}try{g=a.stack||void 0}catch(z){}try{m=a.name||void 0}catch(z){}try{k=a.cause}catch(z){}a=new be(n,{fileName:p,lineNumber:r,columnNumber:t,stack:g,name:m,
cause:k})}if(d===ba){var sd;(sd=A.GM_HAS_SENT_SEVERE)!=null&&sd?d="severe_after_initial":A.GM_HAS_SENT_SEVERE=!0}eb(b,a,d)};var je=Promise;var ke=ha("data");var le=y(),me=function(a,b){b&&(a.onmessage=function(c){var d=c.data;me(c.ports[0]);b(new ke(d))})};var ne=ha("g"),oe=function(a){var b=Object.create(null);(typeof a===x?[a]:a).forEach(function(c){if(c==="null")throw Error("$");b[c]=!0});return function(c){return b[c]===!0}};var md=function(a){var b=a.destination;var c=a.S;var d=a.origin;var e=a.F===void 0?"ZNWN1d":a.F;var h=a.onMessage===void 0?void 0:a.onMessage;a=a.C===void 0?void 0:a.C;pe({destination:b,R:function(){return c.contentWindow},U:d instanceof ne?d:typeof d===u?new ne(d):new ne(oe(d)),F:e,onMessage:h,C:a})},pe=function(a){var b=a.destination;var c=a.R;var d=a.U;var e=a.W===void 0?void 0:a.W;var h=a.F;var f=a.onMessage===void 0?void 0:a.onMessage;var g=a.C===void 0?void 0:a.C;new je(function(k,m){var n=
function(p){p.source&&p.source===c()&&d.g(p.origin)&&(p.data.n||p.data)===h&&(b.removeEventListener("message",n,!1),e&&p.data.t!==e?m(Error("aa`"+h+"`"+e+"`"+p.data.t)):(me(p.ports[0],f),k(new le),g&&g(p)))};b.addEventListener("message",n,!1)})};var qe=y();
qe.prototype.g=function(a,b,c){a=a?a:Error();var d={};d.trace=a.stack;d["context.source"]="INITIAL_LOAD";d["context.severity"]=c===void 0?da:c;d["context.location"]=window.location.href;d["context.build"]=G[54];d["context.buildLabel"]=G[54];c=G[48];c=(d["context.mainPageJsRowKey"]=c===null?c:G[48],d["context.mainPageActiveMods"]=G[49],d);(b=b||a.message)&&(c["context.message"]=b);b="jserror?"+Oa({script:a.fileName||window.location.href,error:b,line:a.lineNumber});a=Oa(c);b=new Request(b,{method:"POST",
headers:{"Content-Type":"application/x-www-form-urlencoded;charset=UTF-8"},body:a});gd(b)};var re=function(){var a=A.GM_MAINPAGE_ERROR_ARRAY;a.push=function(d){ie(d,{G:ba,message:"Early _DumpException report"});return 0};for(var b=P(a),c=b.next();!c.done;c=b.next())ie(c.value,{G:ba,message:"Very early _DumpException report"});a.splice(0,a.length)};var te=function(){var a=this;this.j=window.top;this.g=Object.create(null);this.i=null;se(this,function(b){a.i=b;for(var c in a.g)a.g[c].H||a.g[c].reject(Error("ca`"+c+"`"+b));var d=a.j.document;if(b=d.getElementById(Yc))c=b.parentNode,d=d.createElement("link"),d.dataset.recordedSrc=b.src,c.insertBefore(d,b),c.removeChild(b),d.id=Yc})},se=function(a,b){var c=function(){b.call.apply(b,[null].concat(Kd(Nd.apply(0,arguments))));b=y()};A.top.GM_IS_DEVELOPMENT_MODE||setTimeout(function(){return c(2)},2E4);
a.j.addEventListener("DOMContentLoaded",function(){var d=a.j.document.getElementById(Yc);d&&ud(d)?d.addEventListener(v,function(){return c(0)}):c(1)})},ue=function(a,b){if(a.g[b]!==void 0)return a.g[b];var c,d,e=function(){h.H=!0;c=y();d=y()},h={promise:new Promise(function(f,g){c=f;d=g}),resolve:function(f){c(f);e()},reject:function(f){d(f);e()},H:!1};a.g[b]=h;a.i!==null&&h.reject(Error("ca`"+b+"`"+a.i));return h};te.prototype.set=function(a){for(var b in a)a.hasOwnProperty(b)&&ue(this,b).resolve(a[b])};
te.prototype.get=function(a){var b=ue(this,a),c=b.promise;b.promise=null;return c||Promise.reject(Error("da`"+a))};var zd=/^([^?#]*)(\?[^#]*)?(#[\s\S]*)?/;var xd=null,yd=null;var xe=function(){var a=this,b,c;this.g=!1;this.l=new Promise(function(d,e){b=d;c=e});this.l.catch(y());this.i=null;this.A=function(){clearTimeout(a.i);b(void 0)};this.j=function(d){clearTimeout(a.i);c(d)};ve();we(this)};xe.prototype.v=function(){this.g||we(this)};xe.prototype.m=function(){this.g=A.GM_LC=!0;try{A.localStorage.removeItem("csol")}catch(a){}this.A()};xe.prototype.o=function(){this.g||(clearTimeout(this.i),this.g=!0,ye(),ze(),this.j(Error("ea")))};
var we=function(a){clearTimeout(a.i);a.i=setTimeout(function(){a.g=!0;ye();ze();a.j(Error("fa"))},2E4)},ze=function(){var a,b=(a=A.GLOBALS)!=null?a:[];A.GM_logStreamz("loading_timed_out",{mct:b[109],consecutive_sols:A.GM_CSOL||0,js_loaded:A._jsl,chat_no_gmail_storage:!!b[118]})},ve=function(){try{var a=A.localStorage.getItem("csol");A.GM_CSOL=parseInt(a,10)||0}catch(b){A.GM_CSOL=0}},ye=function(){try{var a=A.localStorage.getItem("csol"),b=parseInt(a,10)||0;A.localStorage.setItem("csol",String(++b))}catch(c){}};var Ae={n:{minWidth:1252,minHeight:640},s:{minWidth:1060,minHeight:590}};var Ad=["ad","chat","contact","contacts","settings"],Bd=["advanced-search","category","create-filter","label","search"],Be=["cv","tl"];A.performance&&A.performance.mark&&A.performance.mark("gm_mp_bf_it");S("_m",tb);S(Xc,lb);S(Xc,lb,A._mp);S(Xc,lb,tb);var Ce=new qe;I.l&&L(I.j,"v");I.l=Ce;I.g&&(Nb(I.g,function(a){this.l.g(a.e,a.i,a.g)},I),I.g=null);try{re()}catch(a){}A.onerror=function(a,b,c,d,e){ie(e,{G:ba,message:"Early window.onerror report",fileName:b,lineNumber:c,columnNumber:d});var h;b=(h=A.GLOBALS)!=null?h:[];Sa("js_error",{mct:b[109],jsstate:[b[0],b[1],window.JS_START_TIME].join("-"),jsmsg:a})};
A.onunhandledrejection=function(a){ie(a.reason,{G:ba,message:"Early window.onunhandledrejection report"})};window._rmNode=function(a){a=a||document.scripts[document.scripts.length-1];a.parentNode.removeChild(a)};S("GM_LC",!1);S("GM_showErrorPage",kb);S("GM_logStreamz",Sa);for(var De=new H(window.location.href),Ee=!1,Fe=P(["pfmls","rdata","zx"]),Ge=Fe.next();!Ge.done;Ge=Fe.next()){var He=Ge.value;De.g.get(He)!=void 0&&(Nc(De.g,He),Ee=!0)}Ee&&window.history.replaceState({},window.document.title,De.toString());
var Ie=window.location.href,Je;(Je=window!=top||window.frameElement!=null?Ie:null)||(Je=Ie.indexOf("nocheckbrowser")!=-1||G[23]||Fa()?null:A.GM_UNSUPPORTED_BROWSER_URL||A.GM_MOOSE_URL);var Ke;if(!(Ke=Je)){document.cookie=$c;if(document.cookie.indexOf($c)==-1)throw kb(12,"Cookies seem to be disabled in your browser. The app requires cookies to be enabled in order to operate"),Error("ha");document.cookie="jscookietest=valid;expires=Thu, 01 Jan 1970 00:00:00 GMT";Ke=null}var Le;
if(!(Le=Ke))a:{var V=Ie,Me=!1;if(Sd("compose")&&Fd(Ua(V,"compose"))){for(var Ne=V,Oe=Ne.search(ac),Pe=0,Qe,Re=[];(Qe=$b(Ne,Pe,"compose",Oe))>=0;)Re.push(Ne.substring(Pe,Qe)),Pe=Math.min(Ne.indexOf("&",Qe)+1||Oe,Oe);Re.push(Ne.slice(Pe));V=Re.join("").replace(Td,"$1");Me=!0}var Se=Sd("th"),Te;if(Te=Sd("view")){var Ue=Ua(V,"view");Te=Mb(Be,Ue)>=0}var Ve=Te,We;if(We=Sd("tf")){var Xe=Ua(V,"tf");We=Mb(Be,Xe)>=0}var Ye=We;if(Se&&(Ve||Ye)){var Ze=Ua(V,"th");if(Ze&&Fd(Ze)){Le=Id(V,"th");break a}}var X,$e=
V,af=$e.indexOf("#");X=af<0?null:$e.slice(af+1);var bf;b:{var cf=Cd(X);if(cf){var df=cf.indexOf(Vc);if(df>-1){bf=Gd(cf.slice(0,df));break b}}bf=!1}var ef=bf;ef&&(V=V.slice(0,V.indexOf(Vc)),X=X.slice(0,X.indexOf(Vc)));var ff=ef||Gd(X);Le=Me&&!ff?V:ff?Jd():null}var gf=Le;if(gf){var hf=top.location,jf;jf=Od.test(gf)?gf:void 0;jf!==void 0&&(hf.href=jf)}var kf=A.GM_MEET_CLIENT_TYPE,lf,mf=parseInt(A.sessionStorage.getItem(ad),10),nf=parseInt(A.sessionStorage.getItem(bd),10),of=(new Date).getTime();
!isNaN(mf)&&!isNaN(nf)&&of>nf+6E4&&(mf=NaN);A.sessionStorage.removeItem(ad);A.sessionStorage.removeItem(bd);lf=isNaN(mf)?vd():mf;Sa("initial_load_attempt",{mct:kf,nt:lf,gapi_version:null,chat_no_gmail_storage:!!A.GM_IS_CHAT_ONLY_REQUEST_NO_GMAIL_STORAGE});var Z=new xe;S("GM_LP",Z.l);S("GM_SLP",Z.v.bind(Z));S("GM_SLC",Z.m.bind(Z));S("GM_SLF",Z.o.bind(Z));var pf=new te;S("_GM_setData",pf.set.bind(pf));S("_GM_getData",pf.get.bind(pf));
var qf=new function(){var a=a===void 0?A.top.GM_STYLESHEET_URLS||[]:a;var b=b===void 0?A.top.GM_INITIAL_PADDING_PREF:b;var c=null;if(a.length==1)c=a[0];else if(a.length==3){c="t";for(var d=P(Object.entries(Ae)),e=d.next();!e.done;e=d.next()){var h=P(e.value);e=h.next().value;h=h.next().value;h="(min-width: "+h.minWidth+"px) and (min-height: "+(h.minHeight+"px)");if(A.matchMedia&&A.matchMedia(h)&&A.matchMedia(h).matches){c=e;break}}c=A.matchMedia&&(A.matchMedia(Uc)&&A.matchMedia(Uc).matches||A.matchMedia(Tc)&&
A.matchMedia(Tc).matches)?a[2]:c=="t"||b=="t"?a[0]:c=="s"||b=="s"?a[1]:a[2]}this.g=c};S("GM_PRELOADED_STYLESHEET_URL",qf.g);var rf=qf.g?new Promise(function(a,b){var c=new XMLHttpRequest;c.open("GET",qf.g);c.addEventListener(v,function(){a(c.response)});c.addEventListener(q,function(){b(Error("ga`"+qf.g+"`"+c.status+"`"+c.statusText))});c.send()}):null;S("GM_PRELOADED_STYLESHEET_PROMISE",rf);A.performance&&A.performance.mark&&A.performance.mark("gm_mp_it");G[13]&&td();
var sf=document.createElement("div");sf.id="chat-world-url";var tf=null;try{tf=ld().toString(),sf.setAttribute("data-src",tf)}catch(a){A.GM_SGUE=a.stack||a.message}document.body.appendChild(sf);A.GM_SGU=tf;
}catch(e){_DumpException(e)}
// Google Inc.
}());</script>
