# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"
    
  workflow_dispatch:
  push:
    branches: ["main", "master"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: diogenesmedeiros
          template: classic
          base: header, activity, community, repositories, metadata, achievements
          config_timezone: America/Sao_Paulo

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%

          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base

          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: C

          plugin_stars: yes
          plugin_topics: yes
          plugin_topics_sort: stars
          plugin_topics_limit: 15